global:
  resolve_timeout: 1s

route:
  receiver: "multi-receiver"  
  group_interval: 10s
  repeat_interval: 1m

receivers:
  - name: "multi-receiver"
    webhook_configs:
      - url: "http://fastapi:8000/incident" 
        send_resolved: true
