
services:
  demo-vm:
    build: .
    container_name: demo-vm
    hostname: cloud-vm
    command: > 
      sh -c "/usr/local/bin/node_exporter --web.listen-address=':9101' > /var/log/node_exporter.log 2>&1 & sleep infinity"
    restart: always  
    ports:
      - "9101:9100"
    volumes:
      - demo-vm-bin:/usr/local/bin
      - demo-vm-etc:/etc
    tty: true
    networks:
      - monitoring

  fastapi:
    build: ./fastapi 
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    restart: always  
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always  
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always  
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  demo-vm-bin:
  demo-vm-etc: